### ISSUE TITLE
[Mapping] Desert Outpost Ammo boxes contain wrong Assualt Rifle Ammo.

### ISSUE THREAD

**Issue by Joe44445** [HaloSpaceStation/HaloSpaceStation13#2422]
The ammo boxes for the MA5B in the Desert Outpost map contain the wrong ammo so you are unable to load them. this makes the MA5B useless due to the limited ammo

**Comment by caelaislinn** [comment]
Fixed #2424

**Comment by Max-023** [comment]
It isn't fixed, really. You did the wrong M118 mags. You put in the DMR mags, not the MA5B mags.


Also, the shotgun shell boxes are wrong. They are vanilla boxes filled with shotgun shells, not our own shotgun shell boxes that you can use to reload. The vanilla boxes have about 1 reload's worth of shells that you have to load individually.
